# Generated by Django 5.2.1 on 2025-05-17 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailrequest_rename_name_customuser_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='gastos',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='user',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='user',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Gasto',
        ),
        migrations.DeleteModel(
            name='Ingreso',
        ),
        migrations.DeleteModel(
            name='Presupuesto',
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
