# Generated by Django 5.2.1 on 2025-05-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_gasto_user_remove_presupuesto_gastos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailRequest',
        ),
    ]
