# Generated by Django 5.2.1 on 2025-05-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailrequest',
            name='msg',
        ),
        migrations.AddField(
            model_name='emailrequest',
            name='email',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
