# Generated by Django 5.2.1 on 2025-05-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
