# Generated by Django 5.2.1 on 2025-05-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_presupuesto_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
