# Generated by Django 5.2.1 on 2025-05-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateField(),
        ),
    ]
