# Generated by Django 5.2.1 on 2025-05-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_tarea_fecha_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateTimeField(),
        ),
    ]
