# Generated by Django 5.2.1 on 2025-05-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_tarea_fecha_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
