# Generated by Django 5.2.1 on 2025-05-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_tarea_finalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='finalizado',
        ),
        migrations.AddField(
            model_name='evento',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
